version: "3.7"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: gorest
      MYSQL_USER: gouser
      MYSQL_PASSWORD: gopwd
    volumes:
      - ./data:/var/lib/mysql
      - ./src/migration.sql:/docker-entrypoint-initdb.d/migration.sql
    expose:
      - 3306
    ports:
      - "3306:3306"
    networks:
      - app-network
  
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: gouser
      PMA_PASSWORD: gopwd
    networks:
      - app-network
  
  app:
    depends_on:
      - mysql
    build: .
    restart: always
    stdin_open: true
    working_dir: /go
    volumes:
      - "./src:/go/app"
    expose:
      - 81
    environment:
      - DB_PORT=3306
      - DB_HOST=mysql
      - DB_NAME=gorest
      - DB_USER=gouser
      - DB_PASS=gopwd
    command: "go run ./app/server.go"
    networks:
      - app-network
      
  nginx:
    depends_on:
      - mysql
      - app
    image: nginx:alpine
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge